//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sharptella.Gen {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sharptella.Gen.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Sharptella.Gen;
        ///
        ///internal enum ReadWriteMode
        ///{
        ///    Read,
        ///    Write,
        ///    ReadWrite
        ///}
        ///
        ///internal enum AddressingMode
        ///{
        ///    Implied,
        ///    Accumulator,
        ///    Immediate,
        ///    Zeropage,
        ///    ZeropageXIndexed,
        ///    ZeropageYIndexed,
        ///    Absolute,
        ///    AbsoluteXIndexed,
        ///    AbsoluteYIndexed,
        ///    Indirect,
        ///    IndirectXIndexed,
        ///    IndirectYIndexed,
        ///    Relative
        ///}
        ///
        ///[AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
        ///internal sealed class CpuInstructionAttribu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Attributes {
            get {
                return ResourceManager.GetString("Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     private void $OP$_immediate()
        ///    {
        ///        m_SavedValue2 = m_Bus.Read(m_Registers.PC);
        ///        ++m_Registers.PC;
        ///        Trace($&quot;$OP$ #${m_SavedValue2:X2}&quot;);
        ///        $OP$(m_SavedValue2);
        ///        m_CurrentOpCodeCycle = 0;
        ///    }
        ///.
        /// </summary>
        internal static string ReadImmediate {
            get {
                return ResourceManager.GetString("ReadImmediate", resourceCulture);
            }
        }
    }
}
