//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sharptella.Gen {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sharptella.Gen.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     private bool $OP$_Accumulator()
        ///    {
        ///        _ = m_Bus.Read(m_Registers.PC);
        ///        Trace($&quot;$OP$ A&quot;);
        ///        $OP$();
        ///        return true;
        ///    }
        ///.
        /// </summary>
        internal static string Accumulator {
            get {
                return ResourceManager.GetString("Accumulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Sharptella.Gen;
        ///
        ///internal enum InstructionType
        ///{
        ///    Custom, 
        ///    Implied,
        ///    Accumulator,
        ///    BranchConditionalRelative,
        ///
        ///    ReadAbsolute,
        ///    ReadAbsoluteXIndexed,
        ///    ReadAbsoluteYIndexed,
        ///    ReadImmediate,
        ///    ReadIndirectXIndexed,
        ///    ReadIndirectYIndexed,
        ///    ReadZeropage,
        ///    ReadZeropageXIndexed,
        ///    ReadZeropageYIndexed,
        ///
        ///    WriteAbsolute,
        ///    WriteAbsoluteXIndexed,
        ///    WriteAbsoluteYIndexed,
        ///    WriteIndirectXIndexed,
        ///    WriteIndirectYIndexed, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Attributes {
            get {
                return ResourceManager.GetString("Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     private bool $OP$_BranchConditionalRelative()
        ///    {
        ///        switch (m_CurrentOpCodeCycle)
        ///        {
        ///            case 1:
        ///                m_SavedValue0 = m_Bus.Read(m_Registers.PC);
        ///                ++m_Registers.PC;
        ///                Trace($&quot;$OP$ ${m_SavedValue0:X2}&quot;);
        ///
        ///                if ($OP$())
        ///                {
        ///                    return true;
        ///                }
        ///                else
        ///                {
        ///                    return false;
        ///                }
        ///            case 2:
        ///                [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BranchConditionalRelative {
            get {
                return ResourceManager.GetString("BranchConditionalRelative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     private bool $OP$_Implied()
        ///    {
        ///        _ = m_Bus.Read(m_Registers.PC);
        ///        Trace($&quot;$OP$&quot;);
        ///        $OP$();
        ///        return true;
        ///    }
        ///.
        /// </summary>
        internal static string Implied {
            get {
                return ResourceManager.GetString("Implied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     private bool $OP$_ReadAbsolute()
        ///    {
        ///        switch (m_CurrentOpCodeCycle)
        ///        {
        ///            case 1:
        ///                m_SavedValue0 = m_Bus.Read(m_Registers.PC);
        ///                ++m_Registers.PC;
        ///                return false;
        ///            case 2:
        ///                m_SavedValue1 = m_Bus.Read(m_Registers.PC);
        ///                ++m_Registers.PC;
        ///                Trace($&quot;$OP$ ${m_SavedValue0:X2}{m_SavedValue1:X2}&quot;);
        ///                return false;
        ///            default:
        ///                m_SavedValue [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReadAbsolute {
            get {
                return ResourceManager.GetString("ReadAbsolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     private bool $OP$_ReadAbsoluteXIndexed()
        ///    {
        ///        switch (m_CurrentOpCodeCycle)
        ///        {
        ///            case 1:
        ///                m_SavedValue0 = m_Bus.Read(m_Registers.PC);
        ///                ++m_Registers.PC;
        ///                return false;
        ///            case 2:
        ///                m_SavedValue1 = m_Bus.Read(m_Registers.PC);
        ///                ++m_Registers.PC;
        ///                Trace($&quot;$OP$ ${m_SavedValue0:X2}{m_SavedValue1:X2},X&quot;);
        ///                return false;
        ///            case 3:
        ///                if  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReadAbsoluteXIndexed {
            get {
                return ResourceManager.GetString("ReadAbsoluteXIndexed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     private bool $OP$_ReadAbsoluteYIndexed()
        ///    {
        ///        switch (m_CurrentOpCodeCycle)
        ///        {
        ///            case 1:
        ///                m_SavedValue0 = m_Bus.Read(m_Registers.PC);
        ///                ++m_Registers.PC;
        ///                return false;
        ///            case 2:
        ///                m_SavedValue1 = m_Bus.Read(m_Registers.PC);
        ///                ++m_Registers.PC;
        ///                Trace($&quot;$OP$ ${m_SavedValue0:X2}{m_SavedValue1:X2},Y&quot;);
        ///                return false;
        ///            case 3:
        ///                if  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReadAbsoluteYIndexed {
            get {
                return ResourceManager.GetString("ReadAbsoluteYIndexed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     private bool $OP$_ReadImmediate()
        ///    {
        ///        m_SavedValue2 = m_Bus.Read(m_Registers.PC);
        ///        ++m_Registers.PC;
        ///        Trace($&quot;$OP$ #${m_SavedValue2:X2}&quot;);
        ///        $OP$(m_SavedValue2);
        ///        return true;
        ///    }
        ///.
        /// </summary>
        internal static string ReadImmediate {
            get {
                return ResourceManager.GetString("ReadImmediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     private bool $OP$_ReadIndirectXIndexed()
        ///    {
        ///        switch (m_CurrentOpCodeCycle)
        ///        {
        ///            case 1:
        ///                m_SavedValue1 = m_Bus.Read(m_Registers.PC);
        ///                ++m_Registers.PC;
        ///                Trace($&quot;$OP$ (${m_SavedValue1:X2},X)&quot;);
        ///                return false;
        ///            case 2:
        ///                _ = m_Bus.Read(m_SavedValue1);
        ///                return false;
        ///            case 3:
        ///                m_SavedValue0 = m_Bus.Read(GetZeropageIndexedNoCarry(m_SavedValue1, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReadIndirectXIndexed {
            get {
                return ResourceManager.GetString("ReadIndirectXIndexed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     private bool $OP$_ReadIndirectYIndexed()
        ///    {
        ///        switch (m_CurrentOpCodeCycle)
        ///        {
        ///            case 1:
        ///                m_SavedValue1 = m_Bus.Read(m_Registers.PC);
        ///                ++m_Registers.PC;
        ///                Trace($&quot;$OP$ (${m_SavedValue1:X2}),Y&quot;);
        ///                return false;
        ///            case 2:
        ///                m_SavedValue0 = m_Bus.Read(m_SavedValue1);
        ///                return false;
        ///            case 3:
        ///                m_SavedValue1 = m_Bus.Read(GetAdd1NoCarry(m_SavedValue1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReadIndirectYIndexed {
            get {
                return ResourceManager.GetString("ReadIndirectYIndexed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     private bool $OP$_ReadWriteAbsolute()
        ///    {
        ///        switch (m_CurrentOpCodeCycle)
        ///        {
        ///            case 1:
        ///                m_SavedValue0 = m_Bus.Read(m_Registers.PC);
        ///                ++m_Registers.PC;
        ///                return false;
        ///            case 2:
        ///                m_SavedValue1 = m_Bus.Read(m_Registers.PC);
        ///                ++m_Registers.PC;
        ///                Trace($&quot;$OP$ ${m_SavedValue0:X2}{m_SavedValue1:X2}&quot;);
        ///                return false;
        ///            case 3:
        ///                m_SavedV [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReadWriteAbsolute {
            get {
                return ResourceManager.GetString("ReadWriteAbsolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     private bool $OP$_ReadWriteAbsoluteXIndexed()
        ///    {
        ///        switch (m_CurrentOpCodeCycle)
        ///        {
        ///            case 1:
        ///                m_SavedValue0 = m_Bus.Read(m_Registers.PC);
        ///                ++m_Registers.PC;
        ///                return false;
        ///            case 2:
        ///                m_SavedValue1 = m_Bus.Read(m_Registers.PC);
        ///                ++m_Registers.PC;
        ///                Trace($&quot;$OP$ ${m_SavedValue0:X2}{m_SavedValue1:X2},X&quot;);
        ///                return false;
        ///            case 3:
        ///               [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReadWriteAbsoluteXIndexed {
            get {
                return ResourceManager.GetString("ReadWriteAbsoluteXIndexed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     private bool $OP$_ReadWriteAbsoluteYIndexed()
        ///    {
        ///        switch (m_CurrentOpCodeCycle)
        ///        {
        ///            case 1:
        ///                m_SavedValue0 = m_Bus.Read(m_Registers.PC);
        ///                ++m_Registers.PC;
        ///                return false;
        ///            case 2:
        ///                m_SavedValue1 = m_Bus.Read(m_Registers.PC);
        ///                ++m_Registers.PC;
        ///                Trace($&quot;$OP$ ${m_SavedValue0:X2}{m_SavedValue1:X2},Y&quot;);
        ///                return false;
        ///            case 3:
        ///               [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReadWriteAbsoluteYIndexed {
            get {
                return ResourceManager.GetString("ReadWriteAbsoluteYIndexed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     private bool $OP$_ReadWriteIndirectXIndexed()
        ///    {
        ///        switch (m_CurrentOpCodeCycle)
        ///        {
        ///            case 1:
        ///                m_SavedValue1 = m_Bus.Read(m_Registers.PC);
        ///                ++m_Registers.PC;
        ///                Trace($&quot;$OP$ (${m_SavedValue1:X2},X)&quot;);
        ///                return false;
        ///            case 2:
        ///                _ = m_Bus.Read(m_SavedValue1);
        ///                return false;
        ///            case 3:
        ///                m_SavedValue0 = m_Bus.Read(GetZeropageIndexedNoCarry(m_SavedVa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReadWriteIndirectXIndexed {
            get {
                return ResourceManager.GetString("ReadWriteIndirectXIndexed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     private bool $OP$_ReadWriteIndirectYIndexed()
        ///    {
        ///        switch (m_CurrentOpCodeCycle)
        ///        {
        ///            case 1:
        ///                m_SavedValue1 = m_Bus.Read(m_Registers.PC);
        ///                ++m_Registers.PC;
        ///                Trace($&quot;$OP$ (${m_SavedValue1:X2}),Y&quot;);
        ///                return false;
        ///            case 2:
        ///                m_SavedValue0 = m_Bus.Read(m_SavedValue1);
        ///                return false;
        ///            case 3:
        ///                m_SavedValue1 = m_Bus.Read(GetAdd1NoCarry(m_SavedV [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReadWriteIndirectYIndexed {
            get {
                return ResourceManager.GetString("ReadWriteIndirectYIndexed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     private bool $OP$_ReadWriteZeropage()
        ///    {
        ///        switch (m_CurrentOpCodeCycle)
        ///        {
        ///            case 1:
        ///                m_SavedValue0 = m_Bus.Read(m_Registers.PC);
        ///                ++m_Registers.PC;
        ///                Trace($&quot;$OP$ ${m_SavedValue0:X2}&quot;);
        ///                return false;
        ///            case 2:
        ///                m_SavedValue2 = m_Bus.Read(m_SavedValue0);
        ///                return false;
        ///            case 3:
        ///                m_Bus.Write(m_SavedValue0, m_SavedValue2);
        ///                re [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReadWriteZeropage {
            get {
                return ResourceManager.GetString("ReadWriteZeropage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     private bool $OP$_ReadWriteZeropageXIndexed()
        ///    {
        ///        switch (m_CurrentOpCodeCycle)
        ///        {
        ///            case 1:
        ///                m_SavedValue0 = m_Bus.Read(m_Registers.PC);
        ///                ++m_Registers.PC;
        ///                Trace($&quot;$OP$ ${m_SavedValue0:X2},X&quot;);
        ///                return false;
        ///            case 2:
        ///                _ = m_Bus.Read(m_SavedValue0);
        ///                return false;
        ///            case 3:
        ///                m_SavedValue2 = m_Bus.Read(GetZeropageIndexedNoCarry(m_SavedValu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReadWriteZeropageXIndexed {
            get {
                return ResourceManager.GetString("ReadWriteZeropageXIndexed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     private bool $OP$_ReadZeropage()
        ///    {
        ///        switch (m_CurrentOpCodeCycle)
        ///        {
        ///            case 1:
        ///                m_SavedValue0 = m_Bus.Read(m_Registers.PC);
        ///                ++m_Registers.PC;
        ///                Trace($&quot;$OP$ ${m_SavedValue0:X2}&quot;);
        ///                return false;
        ///            default:
        ///                m_SavedValue2 = m_Bus.Read(m_SavedValue0);
        ///                $OP$(m_SavedValue2);
        ///                return true;
        ///        }
        ///    }
        ///.
        /// </summary>
        internal static string ReadZeropage {
            get {
                return ResourceManager.GetString("ReadZeropage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     private bool $OP$_ReadZeropageXIndexed()
        ///    {
        ///        switch (m_CurrentOpCodeCycle)
        ///        {
        ///            case 1:
        ///                m_SavedValue0 = m_Bus.Read(m_Registers.PC);
        ///                ++m_Registers.PC;
        ///                Trace($&quot;$OP$ ${m_SavedValue0:X2},X&quot;);
        ///                return false;
        ///            case 2:
        ///                _ = m_Bus.Read(m_SavedValue0);
        ///                return false;
        ///            default:
        ///                m_SavedValue2 = m_Bus.Read(GetZeropageIndexedNoCarry(m_SavedValue0,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReadZeropageXIndexed {
            get {
                return ResourceManager.GetString("ReadZeropageXIndexed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     private bool $OP$_ReadZeropageYIndexed()
        ///    {
        ///        switch (m_CurrentOpCodeCycle)
        ///        {
        ///            case 1:
        ///                m_SavedValue0 = m_Bus.Read(m_Registers.PC);
        ///                ++m_Registers.PC;
        ///                Trace($&quot;$OP$ ${m_SavedValue0:X2},Y&quot;);
        ///                return false;
        ///            case 2:
        ///                _ = m_Bus.Read(m_SavedValue0);
        ///                return false;
        ///            default:
        ///                m_SavedValue2 = m_Bus.Read(GetZeropageIndexedNoCarry(m_SavedValue0,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReadZeropageYIndexed {
            get {
                return ResourceManager.GetString("ReadZeropageYIndexed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     private bool $OP$_WriteAbsolute()
        ///    {
        ///        switch (m_CurrentOpCodeCycle)
        ///        {
        ///            case 1:
        ///                m_SavedValue0 = m_Bus.Read(m_Registers.PC);
        ///                ++m_Registers.PC;
        ///                return false;
        ///            case 2:
        ///                m_SavedValue1 = m_Bus.Read(m_Registers.PC);
        ///                ++m_Registers.PC;
        ///                Trace($&quot;$OP$ ${m_SavedValue0:X2}{m_SavedValue1:X2}&quot;);
        ///                return false;
        ///            default:
        ///                m_Bus.Write [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WriteAbsolute {
            get {
                return ResourceManager.GetString("WriteAbsolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     private bool $OP$_WriteAbsoluteXIndexed()
        ///    {
        ///        switch (m_CurrentOpCodeCycle)
        ///        {
        ///            case 1:
        ///                m_SavedValue0 = m_Bus.Read(m_Registers.PC);
        ///                ++m_Registers.PC;
        ///                return false;
        ///            case 2:
        ///                m_SavedValue1 = m_Bus.Read(m_Registers.PC);
        ///                ++m_Registers.PC;
        ///                Trace($&quot;$OP$ ${m_SavedValue0:X2}{m_SavedValue1:X2},X&quot;);
        ///                return false;
        ///            case 3:
        ///                _  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WriteAbsoluteXIndexed {
            get {
                return ResourceManager.GetString("WriteAbsoluteXIndexed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     private bool $OP$_WriteAbsoluteYIndexed()
        ///    {
        ///        switch (m_CurrentOpCodeCycle)
        ///        {
        ///            case 1:
        ///                m_SavedValue0 = m_Bus.Read(m_Registers.PC);
        ///                ++m_Registers.PC;
        ///                return false;
        ///            case 2:
        ///                m_SavedValue1 = m_Bus.Read(m_Registers.PC);
        ///                ++m_Registers.PC;
        ///                Trace($&quot;$OP$ ${m_SavedValue0:X2}{m_SavedValue1:X2},Y&quot;);
        ///                return false;
        ///            case 3:
        ///                _  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WriteAbsoluteYIndexed {
            get {
                return ResourceManager.GetString("WriteAbsoluteYIndexed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     private bool $OP$_WriteIndirectXIndexed()
        ///    {
        ///        switch (m_CurrentOpCodeCycle)
        ///        {
        ///            case 1:
        ///                m_SavedValue1 = m_Bus.Read(m_Registers.PC);
        ///                ++m_Registers.PC;
        ///                Trace($&quot;$OP$ (${m_SavedValue1:X2},X)&quot;);
        ///                return false;
        ///            case 2:
        ///                _ = m_Bus.Read(m_SavedValue1);
        ///                return false;
        ///            case 3:
        ///                m_SavedValue0 = m_Bus.Read(GetZeropageIndexedNoCarry(m_SavedValue1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WriteIndirectXIndexed {
            get {
                return ResourceManager.GetString("WriteIndirectXIndexed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     private bool $OP$_WriteIndirectYIndexed()
        ///    {
        ///        switch (m_CurrentOpCodeCycle)
        ///        {
        ///            case 1:
        ///                m_SavedValue1 = m_Bus.Read(m_Registers.PC);
        ///                ++m_Registers.PC;
        ///                Trace($&quot;$OP$ (${m_SavedValue1:X2}),Y&quot;);
        ///                return false;
        ///            case 2:
        ///                m_SavedValue0 = m_Bus.Read(m_SavedValue1);
        ///                return false;
        ///            case 3:
        ///                m_SavedValue1 = m_Bus.Read(GetAdd1NoCarry(m_SavedValue [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WriteIndirectYIndexed {
            get {
                return ResourceManager.GetString("WriteIndirectYIndexed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     private bool $OP$_WriteZeropage()
        ///    {
        ///        switch (m_CurrentOpCodeCycle)
        ///        {
        ///            case 1:
        ///                m_SavedValue0 = m_Bus.Read(m_Registers.PC);
        ///                ++m_Registers.PC;
        ///                Trace($&quot;$OP$ ${m_SavedValue0:X2}&quot;);
        ///                return false;
        ///            default:
        ///                m_Bus.Write(m_SavedValue0, $OP$());
        ///                return true;
        ///        }
        ///    }
        ///.
        /// </summary>
        internal static string WriteZeropage {
            get {
                return ResourceManager.GetString("WriteZeropage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     private bool $OP$_WriteZeropageXIndexed()
        ///    {
        ///        switch (m_CurrentOpCodeCycle)
        ///        {
        ///            case 1:
        ///                m_SavedValue0 = m_Bus.Read(m_Registers.PC);
        ///                ++m_Registers.PC;
        ///                Trace($&quot;$OP$ ${m_SavedValue0:X2},X&quot;);
        ///                return false;
        ///            case 2:
        ///                _ = m_Bus.Read(m_SavedValue0);
        ///                return false;
        ///            default:
        ///                m_Bus.Write(GetZeropageIndexedNoCarry(m_SavedValue0, m_Registers.X) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WriteZeropageXIndexed {
            get {
                return ResourceManager.GetString("WriteZeropageXIndexed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     private bool $OP$_WriteZeropageYIndexed()
        ///    {
        ///        switch (m_CurrentOpCodeCycle)
        ///        {
        ///            case 1:
        ///                m_SavedValue0 = m_Bus.Read(m_Registers.PC);
        ///                ++m_Registers.PC;
        ///                Trace($&quot;$OP$ ${m_SavedValue0:X2},Y&quot;);
        ///                return false;
        ///            case 2:
        ///                _ = m_Bus.Read(m_SavedValue0);
        ///                return false;
        ///            default:
        ///                m_Bus.Write(GetZeropageIndexedNoCarry(m_SavedValue0, m_Registers.Y) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WriteZeropageYIndexed {
            get {
                return ResourceManager.GetString("WriteZeropageYIndexed", resourceCulture);
            }
        }
    }
}
